"""empty message

Revision ID: 4e360dc2533b
Revises: 03f133501a64
Create Date: 2024-03-31 18:36:43.735835

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '4e360dc2533b'
down_revision = '03f133501a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mlb_stats_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['mlb_stats_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('mlb_stats_id')

    # ### end Alembic commands ###