from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563rg112x9t8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('mlb_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mlb_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('primary_position', sa.String(length=2), nullable=False),
    sa.Column('average', sa.Float(), nullable=False),
    sa.Column('rbi', sa.Integer(), nullable=False),
    sa.Column('homers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team1_name', sa.String(length=50), nullable=True),
    sa.Column('team1_id', sa.Integer(), nullable=True),
    sa.Column('team1_batter', sa.Integer(), nullable=False),
    sa.Column('team1_runs', sa.Integer(), nullable=False),
    sa.Column('team2_name', sa.String(length=50), nullable=True),
    sa.Column('team2_id', sa.Integer(), nullable=True),
    sa.Column('team2_batter', sa.Integer(), nullable=False),
    sa.Column('team2_runs', sa.Integer(), nullable=False),
    sa.Column('batting', sa.Integer(), nullable=True),
    sa.Column('inning', sa.Integer(), nullable=False),
    sa.Column('top_of_inning', sa.Boolean(), nullable=False),
    sa.Column('end_of_inning', sa.Boolean(), nullable=False),
    sa.Column('balls', sa.Integer(), nullable=False),
    sa.Column('strikes', sa.Integer(), nullable=False),
    sa.Column('outs', sa.Integer(), nullable=False),
    sa.Column('runner1', sa.Integer(), nullable=False),
    sa.Column('runner2', sa.Integer(), nullable=False),
    sa.Column('runner3', sa.Integer(), nullable=False),
    sa.Column('runner4', sa.Integer(), nullable=False),
    sa.Column('current_runner', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team1_id'),
    sa.UniqueConstraint('team1_name'),
    sa.UniqueConstraint('team2_id'),
    sa.UniqueConstraint('team2_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('teams')
    op.drop_table('game')
    # ### end Alembic commands ###