"""empty message

Revision ID: 458b26ea33f9
Revises: 563rg112x9t8
Create Date: 2024-03-06 21:23:59.748426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458b26ea33f9'
down_revision = '563rg112x9t8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team1lineup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('primary_position', sa.String(length=2), nullable=False),
    sa.Column('average', sa.Float(), nullable=False),
    sa.Column('rbi', sa.Integer(), nullable=False),
    sa.Column('homers', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('team2lineup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('primary_position', sa.String(length=2), nullable=False),
    sa.Column('average', sa.Float(), nullable=False),
    sa.Column('rbi', sa.Integer(), nullable=False),
    sa.Column('homers', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team2lineup')
    op.drop_table('team1lineup')
    # ### end Alembic commands ###