"""empty message

Revision ID: ad670099f1de
Revises: 458b26ea33f9
Create Date: 2024-03-10 12:14:57.156483

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'ad670099f1de'
down_revision = '458b26ea33f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('away_lineup', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.Column('home_lineup', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('team1lineup')
    op.drop_table('team2lineup')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team2lineup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('primary_position', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('average', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rbi', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('homers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='team2lineup_pkey'),
    sa.UniqueConstraint('name', name='team2lineup_name_key')
    )
    op.create_table('team1lineup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('primary_position', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('average', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rbi', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('homers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='team1lineup_pkey'),
    sa.UniqueConstraint('name', name='team1lineup_name_key')
    )
    op.drop_table('lineups')
    # ### end Alembic commands ###